openapi: 3.0.0
info:
  title: SFL Prompt Studio API
  version: 1.0.0
  description: Backend API for SFL Prompt Studio, enabling AI-driven workflow and prompt management
  contact:
    name: SFL Prompt Studio Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://api.sflprompt.studio/api
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token-based authentication. Include the token in the Authorization header as 'Bearer <token>'

  schemas:
    PromptSFL:
      type: object
      description: Structured Flexible Language (SFL) Prompt Structure
      properties:
        id:
          type: string
        goal:
          type: string
        tenor:
          type: string
        mode:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/SFLField'

    SFLField:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        type:
          type: string

    Workflow:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    Task:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        agent:
          type: string
        dependencies:
          type: array
          items:
            type: string

    AIProviderStatus:
      type: object
      properties:
        name:
          type: string
        available:
          type: boolean
        health:
          type: string

paths:
  /prompts:
    post:
      summary: Create a new SFL-structured prompt
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptSFL'
      responses:
        '201':
          description: Prompt created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptSFL'
        '400':
          description: Invalid prompt structure

  /workflows:
    post:
      summary: Create a new workflow
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      responses:
        '201':
          description: Workflow created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Invalid workflow structure

  /providers/status:
    get:
      summary: Get AI provider status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Provider status retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AIProviderStatus'

  /gemini/generate-sfl:
    post:
      summary: Generate SFL from goal
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                goal:
                  type: string
      responses:
        '200':
          description: SFL generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptSFL'